### ISSUE TITLE
Email Spam

### ISSUE THREAD

**Issue by stong** [Totodore/socketioxide#107]
Greetings,

Thank you for your wonderful contribution to the open-source and Rust communities. I wanted to discuss this unsolicited email I received today:

> Hi Tong,
> Would you star this repository? https://github.com/Totodore/socketioxide
> It is an open source socket.io implementation in Rust. Your star will help the project gain a lot of momentum.
> Thanks for your time!

The sender is one of the contributors of this repository.

I was wondering if your team was aware of these emails.

Thank you.

**Comment by Totodore** [comment]
Hello, I was absolutely not aware, I'm going to contact @tausifcreates. 

Sorry for the inconvenience

**Comment by Totodore** [comment]
I've sent an email asking him to stop doing that. 

Thank you for the information rather than "blacklisting" the project 😅.

**Comment by tausifcreates** [comment]
Hi @Totodore did you receive my response?
