### ISSUE TITLE
println on socket connect

### ISSUE THREAD

**Issue by RoyalFoxy** [Totodore/socketioxide#12]
I noticed that there is a println that gets called everytime a socket connects which really takes away from logging if smth like the tracing crate is used. So my question is if [this](https://github.com/Totodore/socketioxide/blob/19262bed6d233907d3e29028aa114c38de5a9b74/socketioxide/src/client.rs#L131) is needed or if those println can be removed?

**Comment by Totodore** [comment]
Hey, you are totally right.

It should be removed in the next version.

**Comment by Totodore** [comment]
It is fixed in the #develop branch and it will be merge soon
