### ISSUE TITLE
emit events from background task

### ISSUE THREAD

**Issue by prabirshrestha** [Totodore/socketioxide#132]
I have a scenario where I have a long running example, such as extracting zip files that might happen in the background and would like to show progress or send a message when it is done to the client in realtime.

**Comment by Totodore** [comment]
When you create your layer or your service with `let (layer, io) = SocketIo::new_layer();` you have the `io` handle which is the same than in nodejs. It is a cheaply clonable handle that lets you retrieve any socket. So you can make your socket join a room when it connects and then you can move the handle into your task and when you need to emit a message you can use [`io.to()`](https://docs.rs/socketioxide/latest/socketioxide/struct.SocketIo.html#method.to) and by specifying your socket room.

**Comment by Totodore** [comment]
Note that if you are using a namespace different than `/` you have to select your custom namespace with the `of` operator like this `io.of("/custom_nsp").to("my_socket_room").emit()`
