### ISSUE TITLE
Selecting namespace with `SocketIo::of` requires chaining `broadcast` for subsequent operations

### ISSUE THREAD

**Issue by taesungh** [Totodore/socketioxide#149]
## Description
Operator methods (e.g. `emit`, `sockets`, `disconnect`) which are expected to work the same as equivalent `SocketIo` methods for all sockets do not work properly when selecting a namespace but not a room.

## To Reproduce
1. Load the [background-task example](https://github.com/Totodore/socketioxide/blob/main/examples/background-task/src/main.rs)
2. Connect a client and observe the value of `cnt` is 1 (e.g. `info!(cnt)`).
3. Inside `background_task` function, replace a global operation on `io` with a namespace selection:
    e.g. replace
    ```rust
    let cnt = io.sockets().unwrap().len();
    ```
    with
    ```rust
    let cnt = io.of("/").unwrap().sockets().unwrap().len();
    ```
4. Observe the count is 0 even when a client is connected.

The example here is superfluous, but the issue is relevant when using a namespace other than the main one.

## Expected behavior
Selecting a namespace with `SocketIo::of` should make subsequent operations act on all sockets.

The issue is resolved when using the `Operators::broadcast` operator, e.g.
```rust
let cnt = io.of("/").unwrap().broadcast().sockets().unwrap().len();
```
but this seems counterproductive, especially when the doc comments describe the general operations as aliases
> Alias for `io.of("/").unwrap().emit(event, data)` (`SocketIo::emit`)

## Additional Context
First time working with Rust. Using current latest main: eadd59f.

**Comment by Totodore** [comment]
Hey, can you precise the namespace your client was connected on to reproduce the issue?

**Comment by taesungh** [comment]
Thank you for the quick turnaround, I appreciate your continued work on this!
