### ISSUE TITLE
EngineIO: support standard of protocol

### ISSUE THREAD

**Issue by biryukovmaxim** [Totodore/socketioxide#15]
I launched tests from [here](https://socket.io/docs/v4/engine-io-protocol/#test-suite)
two of them failed:
      1) ignores HTTP requests with same sid after upgrade
      2) ignores WebSocket connection with same sid after upgrade

Protocol says: "A client MUST NOT open more than one WebSocket connection per session. Should it happen, the server MUST close the WebSocket connection." Unfortunately this is not really clear

The real behavior of canonical TS [implementation](https://github.com/socketio/engine.io/blob/1bfa9cd0888481a1a5ff05869114b39c1c47df40/lib/userver.ts#LL184C1-L193C23):
```
        const client = this.clients[id];
        if (!client) {
          debug("upgrade attempt for closed client");
          res.close();
        } else if (client.upgrading) {
          debug("transport has already been trying to upgrade");
          res.close();
        } else if (client.upgraded) {
          debug("transport had already been upgraded");
          res.close();
```
It means they don't try to upgrade connection transport to ws at all in this cases.
on_ws_req_init function should be split in two: upgrading logic(should update or not) and communication part(recv/send messages).

Current behavior: on_ws_req function runs on_ws_req_init  as tokio task, it always(except query problems and smth else) tries to send 101 of switching protocol.

Suggested behavior: call function that will check is upgrading acceptable, then runs tokio task handling messages

**Comment by biryukovmaxim** [comment]
Also I think it would be nice if someone added js test suites to ci or at least to this repo to check correctness of the server implementation

**Comment by Totodore** [comment]
The test suite for socketio is already present in CI : https://github.com/Totodore/socketioxide/actions/workflows/socketio-ci.yml

For the Engine Io test suites it should only fail for : `1) ignores WebSocket connection with same sid after upgrade`
The cause is that the implementation for this test is different between the socketio test suite & the engineio test suite. So I prefered to make the socketio pipeline work.

I opened an issue on the test-suite repo https://github.com/socketio/socket.io-protocol/issues/29

For the error `ignores HTTP requests with same sid after upgrade` it should work.

Which branch did you test ?

**Comment by biryukovmaxim** [comment]
[ignores WebSocket connection with same sid after upgrade](https://github.com/socketio/socket.io-protocol/issues/29)
I tried node.js engine.io server, it had the same behavior, the test failed.

**Comment by biryukovmaxim** [comment]
`ignores HTTP requests with same sid after upgrade` issue is NOOP packet came before 4Hello. 
this it the test log:
```
1) Engine.IO protocol
       upgrade
         ignores HTTP requests with same sid after upgrade:

      AssertionError: expected '6' to deeply equal '4hello'
      + expected - actual

      -6
      +4hello
```

**Comment by Totodore** [comment]
When developing the Chat example (#17) I discovered high latency (10sec) when the socket was upgrading. Maybe it is linked.
