### ISSUE TITLE
use secure cookies for auth

### ISSUE THREAD

**Issue by prabirshrestha** [Totodore/socketioxide#157]
How do I use cookies for auth instead of query string?

I'm currently using salvo and I use cookie for auth which is a jwt token that I don't have access from JS due to `httponly` cookie.

**Comment by Totodore** [comment]
You can access any header made for your request by using `req_parts()` on your `SocketRef`. Because I didn't exported the Socket struct. The doc of Socket is missing on doc.rs :/

**Comment by prabirshrestha** [comment]
I was able to access via `let cookie= &socket.req_parts().headers.get("cookie");`. Probably worth having `.cookies` so we don't need to parse it manually?
 
How do I write async code to validate the user token given I cannot pass async functions.

````rust
async fn on_connect(socket: SocketRef, Data(data): Data<Value>) {
  let cookie= &socket.req_parts().headers.get("cookie").unwrap_or_default();
  if validate_user(cookie).await? {
  }
}
```

**Comment by Totodore** [comment]
You should be able to put async function as handler like this : 
```rust*
socket.on(
    "message",
    |socket: SocketRef, Data::<Value>(data), Bin(bin)| async move {
        info!("Received event: {:?} {:?}", data, bin);
        socket.bin(bin).emit("message-back", data).ok();
    },
);
```

For the .cookie part, it would only be an alias of that `socket.req_parts().headers.get("cookie")` because it would be useless to parse cookies for the case where they are not used. But that might be a good idea to add this alias

**Comment by prabirshrestha** [comment]
it works. Not sure why the first time I tried it showed error.

Probably having cookies() as a function will help. But for now I'm good.
