### ISSUE TITLE
CORS support?

### ISSUE THREAD

**Issue by RoyalFoxy** [Totodore/socketioxide#16]
Is there a way to allow cross origin resource sharing for example if the backend (rust) would be on a different port than the frontend (ts)? Because as of now I couldn't find anything in the documentation that allows me to enable cors or hook into the tower implementation and add it myself in my program

**Comment by Totodore** [comment]
Socketioxide takes advantage of the tower ecosystem.
Therefore you can add this [tower http layer](https://docs.rs/tower-http/latest/tower_http/cors/index.html)  which will handle cors policies.
