### ISSUE TITLE
Add support for yjs backend

### ISSUE THREAD

**Issue by prabirshrestha** [Totodore/socketioxide#163]
Is it possible to add [yjs](https://github.com/yjs/yjs) backend? This would allow us to build collaborative editors using socketioxide. 

Resources:
https://github.com/ivan-topp/y-socket.io
https://github.com/yjs/y-websocket

**Comment by Totodore** [comment]
It would be another crate that would wrap the Io struct. Personally I won't develop that (I still have a lot to do for socketioxide). 

However anyone can make a yjs backend that without additional development for socketioxide :)

**Comment by Totodore** [comment]
Please for the next questions and improvements that are not related to the current codebase itself use the discussions panel :)
