### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by sleeyax** [Totodore/socketioxide#18]
When I run `cargo run` in a project that depends on `socketioxide`, I receive the following error:

```
   Compiling socketioxide v0.2.0
error[E0277]: `EngineIo<Client<A>>` doesn't implement `std::fmt::Debug`
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/socketioxide-0.2.0/src/client.rs:23:5
   |
19 | #[derive(Debug)]
   |          ----- in this derive macro expansion
...
23 |     engine: Weak<EngineIo<Self>>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `EngineIo<Client<A>>` cannot be formatted using `{:?}` because it doesn't implement `std::fmt::Debug`
   |
   = help: the trait `std::fmt::Debug` is not implemented for `EngineIo<Client<A>>`
   = help: the trait `std::fmt::Debug` is implemented for `std::sync::Weak<T>`
   = note: this error originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `socketioxide` due to previous error
```

The issue still occurs when adding the latest `main` branch as a dependency: `socketioxide = {git = "https://github.com/Totodore/socketioxide.git", branch = "main"}`.

My toolchain:

```bash
$ rustup show
# ...
active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.66.0 (69f9c33d7 2022-12-12)
```

**Comment by Totodore** [comment]
Can you try on branch `ft-examples` which will be merged soon and that contains a lot of refactored code. (Notably about debug) ?

Also did you try to compile examples ?

**Comment by sleeyax** [comment]
Thank you for your fast response. 

My project, which is currently heavily based on the example in the README, indeed compiles just fine with the `ft-examples` branch given some minor adjustments  :) I hope this branch gets merged soon, thank you so much for your hard work on this amazing library!

Closing this issue as it will soon be fixed by https://github.com/Totodore/socketioxide/pull/17.
