### ISSUE TITLE
Dynamic Namespaces

### ISSUE THREAD

**Issue by FabianHummel** [Totodore/socketioxide#212]
I have noticed that [dynamic namespaces](https://socket.io/docs/v3/namespaces/#dynamic-namespaces) via regex are not yet implemented. Is this planned?

Is there a way for custom middleware to handle this in the meantime?

**Comment by Totodore** [comment]
It is not planned for the moment. I'll do some research on it and maybe propose directions for anyone who would like to work on it.

**Comment by FabianHummel** [comment]
Is it possible to work around this issue by using custom Middleware in axum or socketioxide to intercept the connection request and create a namespace with `io.ns(request.path /* target path to create dynamically*/)` and later delete it again when the client chooses to close the session? Or maybe preflight a connection attempt on the path "/", create the namespace there, and connect a second time then to the namespace, even though that seems quite cumbersome

**Comment by Totodore** [comment]
At any time you can debug the io struct and you should be able to get the map of the current registered namespaces.

I don't think I'll implement regex based matching or function base matching. If the user add a bad regex or a long-computation function it would slow down routing. I'd like to go the ["axum-way"](https://github.com/tokio-rs/axum/pull/363) and use the [matchit](https://docs.rs/matchit/) crate.

If anyone would like to work on this issue : 
* Replace the `Hashmap` struct in the client with the `Permit` struct
* Throw a panic in case of concurrent route at insertion.
* Add a simple benchmark to verify that routing is constant with a lot of handlers
* Propagate the parameters to the handler and add a `Param` extractor

**Comment by Totodore** [comment]
We need to have node removal feature to use the matchit router : https://github.com/ibraheemdev/matchit/issues/44 as found by @brandonsimpson21.

**Comment by tausifcreates** [comment]
> We need to have node removal feature to use the matchit router : https://github.com/ibraheemdev/matchit/issues/44 as found by @brandonsimpson21.

Do we have nodes in Socketioxide?

**Comment by brandonsimpson21** [comment]
you cannot remove nodes with the [matchit router](https://docs.rs/matchit/latest/matchit/struct.Router.html), but you could use the active nodes to recreate the router on node deletion or verify the nodes active beforehand.

**Comment by Totodore** [comment]
> you cannot remove nodes with the [matchit router](https://docs.rs/matchit/latest/matchit/struct.Router.html), but you could use the active nodes to recreate the router on node deletion or verify the nodes active beforehand.

It is a solution that is quite convoluted. I'll try to propose a PR for node removal for the matchit router before thinking about alternative solutions.

**Comment by tausifcreates** [comment]
@Totodore can we go the regex route and leave the case of engine slowing down due to bad regex upto the user 😄

**Comment by Totodore** [comment]
https://github.com/ibraheemdev/matchit/pull/49

**Comment by tausifcreates** [comment]
> https://github.com/ibraheemdev/matchit/pull/49

I hope they merge it real quick 😂

**Comment by Totodore** [comment]
> https://github.com/ibraheemdev/matchit/pull/49

Merged and released with [matchit 0.8.2](https://docs.rs/matchit/latest/matchit/struct.Router.html#method.remove)
