### ISSUE TITLE
SocketRef inside AckResponses

### ISSUE THREAD

**Issue by FabianHummel** [Totodore/socketioxide#222]
**Is your feature request related to a problem? Please describe.**
I recently wrote a broadcast implementation with acknowledgement from each client, and got frustrated to see that I had no way to know which response came from which socket. This is problematic because the frontend needs to know the client id from the response in order to work.
```rust
socket.on("broadcast", |socket: SocketRef, ack: AckSender, Bin(bin): Bin| async move {
    let client_id = socket.extensions.get::<ClientId>().unwrap().clone();

    let responses = socket.broadcast()
        .timeout(Duration::from_millis(4000))
        .bin(bin)
        .emit_with_ack::<Value>("sqw:data", ClientData { id: client_id }).unwrap()
        .filter(|ack| futures::future::ready(ack.is_ok()))
        .map(|ack| {
            let ack = ack.unwrap();
            return (ack.data, ack.binary);
        })
        .collect::<Vec<_>>().await

    // ???
});
```

**Describe the solution you'd like**
I have looked at the internal codebase and found out that the socket could be placed inside the Acknowledgement [here](https://github.com/Totodore/socketioxide/blob/462f95baa1b1f8f585c6989ce3fd344599b1fab7/socketioxide/src/socket.rs#L580C8-L580C8). The problem with this solution is however that I had problems with getting a SocketRef inside here, as the function is written in Socket<A> and has nothing to do with SocketRef. I would like the solution to look something like this:
```rust
Ok(AckResponseWithClient {
    client: /* self.clone() */, // not possible to get the SocketRef here. Or is it?
    data: serde_json::from_value(v.data)?,
    binary: v.binary,
})
```
where AckResponseWithClient is just a copy of the regular AckResponse, just with an extra field:
```rust
#[derive(Debug)]
pub struct AckResponseWithClient<T> {
    /// The subject of the acknowledgement
    pub client: SocketRef,
    /// The data returned by the client
    pub data: T,
    /// Optional binary payloads
    ///
    /// If there is no binary payload, the `Vec` will be empty
    pub binary: Vec<Vec<u8>>,
}
```

**Comment by Totodore** [comment]
Hey, I will add the `SocketRef` inside the `AckResponse` in the PR #201.

**Comment by Totodore** [comment]
There will be only the socket id provided along with the ack response and not the `SocketRef`. Because if we put the `SocketRef` inside the `AckStream`, if we disconnect it while waiting for the acknowledgement, a reference of the socket would still exist in the `AckStream` and therefore an `AckError(SocketError::Closed)` would not be returned as there is still an existing reference.

The best solution I found is therefore to only keep the socket id. You can get any socket in O(1) time with `io.get_socket(Sid)` though.

**Comment by tausifcreates** [comment]
Good thinking!
@FabianHummel you might be interested in this discussion
