### ISSUE TITLE
Feature reqwest: List all rooms

### ISSUE THREAD

**Issue by alakhpc** [Totodore/socketioxide#247]
**Is your feature request related to a problem? Please describe.**
Ability to list all active rooms.

**Describe the solution you'd like**

Something similar to the node server:
```rs
const rooms = io.of("/").adapter.rooms
```

**Comment by Totodore** [comment]
Resolved with #248 and released in v0.10.2 :
https://docs.rs/socketioxide/0.10.2/socketioxide/struct.SocketIo.html#method.rooms
