### ISSUE TITLE
Using TLS to encrypt all messages

### ISSUE THREAD

**Issue by arthurguedes375** [Totodore/socketioxide#251]
**Is your feature request related to a problem? Please describe.**
I would like to be able to chat through websockets but making every message be encrypted.

**Describe the solution you'd like**
Some way to just set a certificate and just work out of the box. (something like the python socketio client, where you just set the keys and you're good to go)

**Describe alternatives you've considered**
encrypting it manually before the requests

**Comment by Totodore** [comment]
@arthurguedes375 TLS encryption is done _in front of_ socketioxide with the http framework you use. I provided an example with axum in the related PR but it can be done with any http framework.

**Comment by arthurguedes375** [comment]
> @arthurguedes375 TLS encryption is done _in front of_ socketioxide with the http framework you use. I provided an example with axum in the related PR but it can be done with any http framework.

Thanks man !
