### ISSUE TITLE
Socket-io client does not upgrade to Websocket, it just works as polling

### ISSUE THREAD

**Issue by Henrriky** [Totodore/socketioxide#264]
**Is your feature request related to a problem? Please describe.**
Yes. Connection does not upgrade to websocket automatically

**Describe the solution you'd like**
I would like the connection on the side to receive the upgrade to websocket, it is keeping it as polling and does not upgrade

**Describe alternatives you've considered**
I don't know if I need to pass any parameters to allow this behavior, if there is something like that please let me know.

**Additional context**
Below is a photo of the behavior that I'm not expecting.
![Captura de tela 2024-02-11 151651](https://github.com/Totodore/socketioxide/assets/70419346/0bfdad11-ac5d-4e72-adff-a1395d1e062d)

**Comment by Totodore** [comment]
Could you please add a demo code of the client and server? Without this I won't be able to see what's wrong.
I suspect that it is the client that is not configured correctly to upgrade to websocket. As it is the responsability of the client to initialize a websocket upgrade request.

**Comment by Henrriky** [comment]
I managed to fix it, in fact, transports was missing: ["polling", "websocket"]. I had only defined polling.


Taking advantage, I would like to know why the emit that I am triggering when the user connects is going along with the Socketioxide connection process?

Here below is an example:

![image](https://github.com/Totodore/socketioxide/assets/70419346/f78f7e9f-84a4-45c1-8405-7d07f0a58f32)

Now notice the second image, which indicates where the emitted data is being received:

![image](https://github.com/Totodore/socketioxide/assets/70419346/0d379e62-cc9f-44c9-adcc-f4d69159e1da)
```rust
Part of the code that accomplishes this:
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    tracing::subscriber::set_global_default(FmtSubscriber::default())?;

    let messages = state::MessageStore::default();
    let sockets = state::SocketDataStore::default();

    let (layer, io) = SocketIo::builder().with_state(messages).with_state(sockets).build_layer();
    
    io.ns("/", |socket: SocketRef, Data(auth): Data<types::AuthData>, store: State<state::SocketDataStore>| async move {

               fn emit_wrapper(event: String, socket: &SocketRef, id: String, data: impl serde::Serialize) {
                    let _result = socket
                    .within(id)
                    .emit(event, data).ok();
                }

                emit_wrapper("person:connected".to_string(), &socket, socket_data.clone().id.clone().to_string(),
                    types::PersonConnected {
                        user_id: socket_data.clone().user_id,
                        extension: socket_data.clone().extension.clone().unwrap_or("".to_string()),
                    }
                );
    });
        let app = axum::Router::new()
        .route("/", get(|| async { "Hello, World!" }))
        .route("/hello", get(handler))
        .with_state(io)
        .layer(
            ServiceBuilder::new()
                .layer(CorsLayer::permissive())
                .layer(layer),
        );

    info!("Starting server");

    axum::Server::bind(&"0.0.0.0:3010".parse().unwrap())
        .serve(app.into_make_service())
        .await?;

    Ok(())
}
```

**Comment by Totodore** [comment]
Because the protocol specification doesn't specify that the initial connect response should be alone. And with http polling it is possible to have multiple packets in one response:
* https://socket.io/docs/v4/engine-io-protocol/#http-long-polling-1

So for performance reasons if two packets are emitted at almost the same time they will be buffered.
https://github.com/Totodore/socketioxide/blob/a11edd6017e7d130de82b5d2979fe09781f8701d/engineioxide/src/transport/ws.rs#L239-L247
