### ISSUE TITLE
SocketIO: Lots of panics on unwrap in case of there are lots of clients

### ISSUE THREAD

**Issue by biryukovmaxim** [Totodore/socketioxide#27]
error:
```
panicked at '14called `Result::unwrap()` on an `Err` value: PoisonError { .. }
', thread 'socketioxide/src/ns.rstokio-runtime-worker:' panicked at '104called `Result::unwrap()` on an `Err` value: PoisonError { .. }:', 14socketioxide/src/ns.rs
:104:14
```
How to reproduce:
run socketio server(i used main) `cargo run --release --bin socketioxide-e2e`
run js clients [client.zip](https://github.com/Totodore/socketioxide/files/11797832/client.zip)

For me it reproduces even with 100 clients.

also I locally tried to replace RWlock<Hashmap> to Dashmap and errors dissappear

**Comment by Totodore** [comment]
Iit is weird that there are poisoned locks because locks appear only in the `get_socket()` fn in `EngineIo` and when inserting a new socket. I'm curious about the poisoned lock origin

If it works with dashmap without too much overhead we could try to switch

**Comment by biryukovmaxim** [comment]
my logs was a consequence, not an error
so the real unwrap is [here](https://github.com/Totodore/socketioxide/blob/0bd8881e407d47bcf37ce4fbbd9ffecfdeff700c/socketioxide/src/socket.rs#L362)

**Comment by Totodore** [comment]
Ah ! You found the real issue :). We need to fix the TODO by mapping the error to the returned Result rather than unwrapping.
I think this happened if the socket is being closed and that you are sending data in the meantime.

**Comment by biryukovmaxim** [comment]
> Ah ! You found the real issue :). We need to fix the TODO by mapping the error to the returned Result rather than unwrapping. I think this happened if the socket is being closed and that you are sending data in the meantime.

Also it's related to my client example, it tries to send 10000 messages asynchronously, but default buffer of packets only 128, when I limited clients to send no more than 120 messages - all was good.

I will return error instead of unwrap, but actually we should think how to handle it correctly:
in case of disconnect we should ignore this error
 but for all other situations mb we should just skip message not making failed all upper level function
