### ISSUE TITLE
Several handlers for a single event

### ISSUE THREAD

**Issue by PhiSyX** [Totodore/socketioxide#274]
**Is your feature request related to a problem? Please describe.**
Hello. Is it in the plans to be able to define several handlers for a single event?
Currently, only one handler is listening when an event is received, the last one in the example below.

**Describe the solution you'd like**
```rust
socket.on("event name", |socket: SocketRef| {
    println!("Hello");
});

socket.on("event name", |socket: SocketRef| {
    println!("World");
});
```

**Comment by Totodore** [comment]
No, it is not planned. The official js implementation doesn't support that either.
However middlewares will be supported with #270

**Comment by PhiSyX** [comment]
Ok, thanks for the answer. :)

But the official JS implementation supports this feature. I've used it several times in JS. That's why I came to ask here.

https://socket.io/docs/v4/server-api/#serveroneventname-listener
> server.on(eventName, listener)
> ...
> Adds the listener function to the end of the listeners array for the event named eventName.

It works in JS on both the server and client sides:  
```js
io.on("connection", (socket) => {
  socket.on("chat message", (msg) => {
    console.log(`Hello: ${msg}`);
  });

  socket.on("chat message", (msg) => {
    console.log(`World: ${msg}`);
  });
});
```
