### ISSUE TITLE
Benchmark and replace Rwlock Hashmap

### ISSUE THREAD

**Issue by biryukovmaxim** [Totodore/socketioxide#28]
I suggest to bench alternatives like
[flurry](https://github.com/jonhoo/flurry)
[dashmap](https://docs.rs/dashmap/latest/dashmap)
comparing to Hashmap.

Also it's possible to create Map trait, implement all options for this trait and give opportunity to user to pick what they wants.
It can be implemented as generic param or feature

**Comment by Totodore** [comment]
Yes I agree that we should bench solutions.

Did you switch to `Dashmap<Sid, Socket>` or `Dashmap<Sid, Arc<Socket>>` ?

**Comment by biryukovmaxim** [comment]
> Yes I agree that we should bench solutions.
> 
> Did you switch to `Dashmap<Sid, Socket>` or `Dashmap<Sid, Arc<Socket>>` ?

`Dashmap<Sid, Arc<Socket>>`

**Comment by Totodore** [comment]
It seems that there is a lot of slowdowns especially with high number of sockets. 
It is important to benchmark a lot to find hotspots and maybe fix some bottlenecks.

DashMaps might be a solution to some of these bottlenecks.

**Comment by biryukovmaxim** [comment]
I picked socketio-e2e,
switched log level to info,
ran flamegraph-rs
ran the script attached below multiple times:

<details>
  <summary>JS client script</summary>

  ```
  import { WebSocket } from "ws";

const URL = "http://localhost:3000";
const WS_URL = URL.replace("http", "ws");

function waitFor(socket, eventType) {
    return new Promise((resolve) => {
        socket.addEventListener(
            eventType,
            (event) => {
                resolve(event);
            },
            { once: true }
        );
    });
}

async function initSocketIOConnection() {
    const socket = new WebSocket(
        `${WS_URL}/socket.io/?EIO=4&transport=websocket`
    );
    socket.binaryType = "arraybuffer";

    await waitFor(socket, "message"); // Engine.IO handshake

    socket.send("40");

    await waitFor(socket, "message"); // Socket.IO handshake
    await waitFor(socket, "message"); // "auth" packet

    return socket;
}

async function runClient(i) {
    let a  = 0;
    const socket = await initSocketIOConnection();
    let message = `42["message","hello${a} from ${i}"]`
    socket.send(message)
    const { data } = await waitFor(socket, "message");
    while (a < 120) {
        // console.log(data);
        // console.log(message);

        if (data === message.replace("message", "message-back")) {
            a += 1;
            let message = `42["message","hello${a} from ${i}"]`
            // console.log(`send message: ${message}`)
            socket.send(message);
        }
        if (data === "2") {
            socket.send("3")
        }
    }
    socket.close()
    runClient(i)
}

// Create 1000 clients
for (let i = 0; i < 1000; i++) {
    runClient(i);
}
  ```
</details>flamegraph:
This flamegraph:
[initial_flamegraph.svg](https://github.com/Totodore/socketioxide/assets/59533214/ace67354-04fe-4de6-93c0-982c0c0d94b0)

it doesn't look like there is a problem in hashmap, but there are lots of convertion of String to Packet

**Comment by Totodore** [comment]
So apparently it is not a limitation to use `RwLock` hashmaps. Closing.
