### ISSUE TITLE
Unnecessary panic on Message enum match arms

### ISSUE THREAD

**Issue by ArchangelJTW** [Totodore/socketioxide#319]
**Describe the bug**
Some of the match arms for tungstenite's `Message` enum in engineioxide/src/transport/ws.rs line 194 are not done, and therefore panic!  I don't think it should panic, because some libraries use the other message variants, for example Pong. The catchall should just log to tracing instead of panicking.

**To Reproduce**
Try a client (doghappy's C# SocketIOClient) that uses the other message enum variants

**Expected behavior**
Not panicking for no reason

**Versions (please complete the following information):**
 - Socketioxide version: v0.13.0
 - Http lib: salvo v0.67.0
 - Socket.io client version: V4
 
**Additional context**
There is none, thanks

**Comment by acfsmith** [comment]
I have the same problem with my client application written in Flutter.  Apart from frequent panics, Socketioxide works just fine.

**Comment by Totodore** [comment]
Fixed with [v0.13.1](https://github.com/Totodore/socketioxide/releases/tag/v0.13.1). Thanks for the report!
