### ISSUE TITLE
`on_disconnection` cannot accept non anonymous functions

### ISSUE THREAD

**Issue by hlf20010508** [Totodore/socketioxide#322]
**Describe the bug**
`on_disconnection` can accept closures but not non anonymous functions.

The function is called `disconnect`.
The error is
```rust
the trait bound `for<'a> fn(&'a socketioxide::extract::SocketRef) {disconnect}: DisconnectHandler<LocalAdapter, _>` is not satisfied
the trait `DisconnectHandler<LocalAdapter, _>` is not implemented for fn item `fn(&SocketRef) {disconnect}`
```

**To Reproduce**
```rust
pub fn disconnect(socket: &SocketRef) {}

let (socketio_layer, socketio) = SocketIo::new_layer();

socketio.ns(
    "/",
    |socket: SocketRef| {
        // socket.on_disconnect(|socket: SocketRef| {}); // this works
        socket.on_disconnect(disconnect); // this not
    },
);
```

**Expected behavior**
The example in doc says
```rust
async fn handler(s: SocketRef, reason: DisconnectReason) {
    tokio::time::sleep(std::time::Duration::from_secs(1)).await;
    println!("Socket disconnected on {} namespace with id and reason: {} {}", s.ns(), s.id, reason);
}

let (svc, io) = SocketIo::new_svc();

// You can reuse the same handler for multiple sockets
io.ns("/", |s: SocketRef| {
    s.on_disconnect(handler);
});
io.ns("/admin", |s: SocketRef| {
    s.on_disconnect(handler);
});
```

But actually this doesn't work.

**Versions (please complete the following information):**
 - Socketioxide version: [0.13.1]
 - Http lib: [axum 0.7.5]
 - Socket.io client version [rust-socketio 0.6.0]
 
**Additional context**
I don't know if there's something that I missed.

**Comment by Totodore** [comment]
You are taking `SocketRef` by ref whereas you should take it by value:

`pub fn disconnect(socket: &SocketRef) {}` Vs `pub fn disconnect(socket: &SocketRef) {}`

**Comment by hlf20010508** [comment]
It works.
Thanks for your help.

**Comment by hlf20010508** [comment]
By the way, you missed code block end "```" here.
https://github.com/Totodore/socketioxide/blob/9415e058ecd6aa509f6199f35d0097ee81768e14/socketioxide/src/socket.rs#L259
