### ISSUE TITLE
Handlers are blocking on new connections.

### ISSUE THREAD

**Issue by JaydenElliott** [Totodore/socketioxide#373]
**Describe the bug**

> If they are async, a new task will be spawned for each incoming connection/message so it doesn’t block the event management task.

Not sure if i'm doing something incorrectly, however this doesn't seem to be true.  Handlers don't seem to spawn tasks correctly (or only have access to a single thread) as they are blocking.

**To Reproduce**

1. Setup socket.io server:
```rust

use axum::Router;
use socketioxide::{extract::SocketRef, SocketIo};
use std::{thread::sleep, time::Duration};

#[tokio::main]
async fn main() {
    let (layer, io) = SocketIo::new_layer();
    io.ns("/", |socket: SocketRef| {
        socket.on("test-fn", |socket: SocketRef| async move {
            println!("client connected"); // <---- Point 1

            // simulate some synchronous processing
            sleep(Duration::from_secs(5)); // < ---- Point 2

            // simulate async processing
            tokio::time::sleep(std::time::Duration::from_secs(5)).await; // <---- Point 3
            socket.emit("test-resp", 123).ok();
        });
    });

    let app = Router::new().layer(layer);
    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await.unwrap();

    axum::serve(listener, app).await.unwrap();
}
```

2. Use two seperate socket.io client's and hit `http://0.0.0:3000`, one immediately after the other.

- The first client will connect and "client connected" will be printed. 
- The second client will not start connecting until either an async point is hit (Point 3) or the first client finishes processesing (5 seconds later).

**Expected behavior**
I would expect it to work like Axum. Client two should able to connect immediately because multiple threads are available within the tokio runtime. 

A working axum example:
```rust
#[tokio::main]
async fn main() {
    let app = Router::new().route("/", get(root));

    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000").await.unwrap();
    axum::serve(listener, app).await.unwrap();
}

async fn root() -> &'static str {
 // simulate processing   
 sleep(Duration::from_secs(5));
    "Hello, World!"
}
```
- Multiple clients are able to connect and "begin processing"

**Versions (please complete the following information):**
 - Socketioxide version: 0.14.1
 - Http lib: [e.g. axum 0.7.6
 - Socket.io client version: js v4.7.5

**Comment by Totodore** [comment]
You are using a blocking version of sleep  which means it will block the entire thread, not just the task.
You should use async alternatives from the Tokio lib and everything will be ok.
The axum example should have the exact same issue though.
https://docs.rs/tokio/latest/tokio/time/fn.sleep.html

**Comment by Totodore** [comment]
If you want to do CPU bound computation it is the same issue as with any other Tokio based lib: you should use `block_on` to have a dedicated thread:
https://docs.rs/tokio/latest/tokio/#cpu-bound-tasks-and-blocking-code

**Comment by JaydenElliott** [comment]
> If you want to do CPU bound computation it is the same issue as with any other Tokio based lib: you should use `block_on` to have a dedicated thread:
> https://docs.rs/tokio/latest/tokio/#cpu-bound-tasks-and-blocking-code


Ah, this is what I was looking for. Thank you 🙏
