### ISSUE TITLE
First ping is sent twice repeatedly

### ISSUE THREAD

**Issue by AkiraMiyakoda** [Totodore/socketioxide#390]
**Describe the bug**
The first ping packet is sent twice repeatedly (see the red rectangle). The subsequent ones are sent normally (see the blue rectangles).

![ping_twice](https://github.com/user-attachments/assets/2d545293-89fa-4e26-8196-1ebee535ca78)

**Expected behavior**
The first ping is sent only once.

**Versions (please complete the following information):**
 - Socketioxide version: 0.15.0
 - Http lib: axum 0.7.7
 - Socket.io client version: socket.io-client 4.8.1 on Microsoft Edge 130.0.2849.56 (Windows 11 23H2 x64)

**Additional Context**
I found this behavior with the WebSocket trasnport. Long polling is not tested.

**Comment by Totodore** [comment]
Could you add debug logs of the server if possible? You have to enable the tracing feature on socketioxide and set the error level to TRACE.

**Comment by AkiraMiyakoda** [comment]
@Totodore 
Here is the log. I hope this would help.
[trace.log](https://github.com/user-attachments/files/17566218/trace.log)

**Comment by Totodore** [comment]
Fixed with #392
