### ISSUE TITLE
Major memory leaks when using Socketioxide

### ISSUE THREAD

**Issue by tristanpoland** [Totodore/socketioxide#399]
**Describe the bug**
Serious memory leak occurs when many connected clients send messages to the server

**To Reproduce**
1. Write any basic socketioxide server (no need to handle socket events)
2. Let a bunch of clients join (we used 1k)
3. Set the clients up to send any socket message rapidly (we used 10ms intervals)
4. Let it run and watch memory climb

**Expected behavior**
After all clients have connects so long as the server is not allocating data anywhere memory should stay static

**Versions (please complete the following information):**
 - Socketioxide version: 0.15.1
 - Http lib: axum 0.7.9
 - Socket.io client info (JS):
 ```
    "socket.io": "4.7.5",
    "socket.io-client": "4.7.5"
 ```
 
**Tested on:**
Windows:
```
i9-11900H + 32GB DDR4 @ 3200 MT/s (Win 11 23H2 OC Build 22631.4460)
Ryzen 9 5950x+ 64GB DDR4 @ 3200MT/s  (Windows 11 Enterprise 23H2 OC Build 22631.4460)
```
Linux:
```
i9-11900H + 32GB DDR4 @ 3200 MT/s (Win 11 23H2 OC Build 22631.4460)
Ryzen 9 5950x+ 64GB DDR4 @ 3200MT/s  (Windows 11 Enterprise 23H2 OC Build 22631.4460)
```
 
**Additional context**
The really interesting part here is after all clients are gone it continues to go up quite a bit and then eventually drops off but not nearly to idle levels.

We are also looking through D-Hat data the prime suspect so far seems to be: ```socketioxide_parser_common::ser::serialize_packet```

The data our team collected can be viewed here:
https://nnethercote.github.io/dh_view/dh_view.html
Here is the data itself:
[dhat-heap(1).json](https://github.com/user-attachments/files/17964125/dhat-heap.1.json)

**Comment by tristanpoland** [comment]
Here is the specific data we collected on the standard allocator with our multi-threaded socket server: 
![image](https://github.com/user-attachments/assets/074dc6f1-be00-4853-a11e-5149fe7100f8)

**Comment by Caznix** [comment]
For reference, in the process of refactoring we came across this bug minimally in this repo while doing a refactor: https://github.com/Caznix/Horizon2

This same bug can also be observed in the main project which uses Viz as a backend rather then Axum: https://github.com/Far-Beyond-Dev/Horizon

The same memory leaking pattern can be observed and sometimes exaggerated using other allocators (such as mimallac) and is consistent throughout all platforms we have tested

**Comment by Totodore** [comment]
Hey, thanks for the report.

It seems that the leak comes from this allocated `Bytes`, a reference to it may be held somewhere whereas it is already sent. https://github.com/Totodore/socketioxide/blob/main/crates%2Fparser-common%2Fsrc%2Fser.rs#L11

**Comment by tristanpoland** [comment]
Worked on this issue in #400 Should no longer be a problem assuming that fn was the only leak

**Comment by Totodore** [comment]
Could you publish a minimal reproducible example ? Either here or in a gist.

**Comment by Totodore** [comment]
After checking the minimal example the issue come from this:

https://github.com/Far-Beyond-Dev/Horizon-Benchmark/blob/a3a85492ff3e1f06124ca9aa34a6fc55fd081d0f/index.js#L62-L66

The `SIGINT` handler should be called for each socket in order to have a graceful shutdown but it calls `process.exit()` so this is only triggered for the first socket and all the other sockets are not being close leading to the 25s heartbeat timeout.

With a fixed client script : 
```js
const io = require('socket.io-client');

const SERVER_URL = 'http://localhost:3000'; // Change this to your server URL
const NUM_CLIENTS = 100; // Change this to the number of clients you want to simulate
const SEND_INTERVAL = 10; // Interval in milliseconds for sending data

const sockets = [];
// Function to generate custom message and body
function generateCustomMessage(clientId) {
    return {
        eventName: 'whisper', // You can change this to any event name you want
        body: {
            clientId: clientId,
            timestamp: Date.now(),
            message: `Custom message from Client ${clientId}`,
            data: {
                value: Math.random(),
                isActive: true,
                tags: ['test', 'custom', `client${clientId}`]
            }
        }
    };
}

// Function to simulate a client connection
function simulateClientConnection(clientId) {
    let attemptCount = 0;
    const socket = io.connect(SERVER_URL, {
        reconnection: true,
        reconnectionAttempts: 5,
        reconnectionDelay: 1000,
        transports: ["polling"]
    });
    sockets.push(socket);

    const logConnectingMessage = () => {
        attemptCount++;
        console.log(`Client ${clientId} connecting... Attempt ${attemptCount}`);
    };

    socket.on('connect', () => {
        attemptCount = 0;
        console.log(`Client ${clientId} connected: ${socket.id}`);

        // Simulate sending custom data to the server
        const intervalId = setInterval(() => {
            const customMessage = generateCustomMessage(clientId);
            socket.emit(customMessage.eventName, customMessage.body);
            console.log(`Client ${clientId} sent: ${JSON.stringify(customMessage)}`);
        }, SEND_INTERVAL);

        socket.on('disconnect', (reason) => {
            console.log(`Client ${clientId} disconnected: ${reason}`);
            clearInterval(intervalId);
        });

        socket.on('error', (error) => {
            console.error(`Client ${clientId} error: ${error}`);
        });
    });

    logConnectingMessage();
    socket.on('reconnect_attempt', logConnectingMessage);
}

process.on('SIGINT', () => {
	for (const socket of sockets)
    	socket.disconnect();
});

// Simulate connections for each client
for (let i = 1; i <= NUM_CLIENTS; i++) {
    simulateClientConnection(i);
}
```

![image](https://github.com/user-attachments/assets/c4f3a0cf-a805-4602-861e-f50090b685be)

Feel free to reopen this, open a discussion thread or another issue if you keep having problems.

**Comment by tristanpoland** [comment]
> So what I conclude is that it is more an issue related to sockets not being closed properly. Either from the client side or from the server side. However it appears that even if they are not closed properly after the ping delay + timeout (~25s) by default everything is cleaned up: ![image](https://private-user-images.githubusercontent.com/26095587/391588936-e0d0af02-c17f-4621-8cd2-3dd2199aa3da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTI4ODcsIm5iZiI6MTczMzE1MjU4NywicGF0aCI6Ii8yNjA5NTU4Ny8zOTE1ODg5MzYtZTBkMGFmMDItYzE3Zi00NjIxLThjZDItM2RkMjE5OWFhM2RhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE1MTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYjViODg2ZDMxNWE5MWIyNWQ4OTdiN2ZhOTI2ZjhlOTdmZWFlNzY3NDg4NzVhYjgxYzU5Y2E0ODQzNmQzZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JhQOnWDkMmpZ6Yx-mMHvxzSFNyRTzR9z3QNny21zdS0)
> 
> I'll investigate to check why they are not removed before the timeout, but it is not as critic as it seems to be.
> 
> @tristanpoland could you confirm on your side that after ~30s memory is correctly cleaned up?


So without handling the disconnects the memory stays up (64M above baseline) even after 30 sec.

With the corrected client code that hangs up properly the memory spikes after the disconnects are called but never goes back down to normal:

- Idle memory:
![Screenshot 2024-12-02 104827](https://github.com/user-attachments/assets/72154c25-c78a-4e37-a9da-78860f9e9c99)

- Clients connected peak memory:
![Screenshot 2024-12-02 104851](https://github.com/user-attachments/assets/b32de86e-d18e-4223-a9d9-b52236dedc35)

-  ~1min after properly handled client disconnect and disconnect spike:
![Screenshot 2024-12-02 104927](https://github.com/user-attachments/assets/b838a8c4-5f24-4c47-80e9-852fdfcfdb0e)

It seems strange that would be environment-dependent, honestly not sure what could be going on here.

**Comment by Totodore** [comment]
> > So what I conclude is that it is more an issue related to sockets not being closed properly. Either from the client side or from the server side. However it appears that even if they are not closed properly after the ping delay + timeout (~25s) by default everything is cleaned up: ![image](https://private-user-images.githubusercontent.com/26095587/391588936-e0d0af02-c17f-4621-8cd2-3dd2199aa3da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTI4ODcsIm5iZiI6MTczMzE1MjU4NywicGF0aCI6Ii8yNjA5NTU4Ny8zOTE1ODg5MzYtZTBkMGFmMDItYzE3Zi00NjIxLThjZDItM2RkMjE5OWFhM2RhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE1MTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYjViODg2ZDMxNWE5MWIyNWQ4OTdiN2ZhOTI2ZjhlOTdmZWFlNzY3NDg4NzVhYjgxYzU5Y2E0ODQzNmQzZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JhQOnWDkMmpZ6Yx-mMHvxzSFNyRTzR9z3QNny21zdS0)
> > 
> > I'll investigate to check why they are not removed before the timeout, but it is not as critic as it seems to be.
> > 
> > @tristanpoland could you confirm on your side that after ~30s memory is correctly cleaned up?
> 
> 
> So without handling the disconnects the memory stays up (64M above baseline) even after 30 sec.
> 
> With the corrected client code that hangs up properly the memory spikes after the disconnects are called but never goes back down to normal:
> 
> - Idle memory:
> ![Screenshot 2024-12-02 104827](https://github.com/user-attachments/assets/72154c25-c78a-4e37-a9da-78860f9e9c99)
> 
> - Clients connected peak memory:
> ![Screenshot 2024-12-02 104851](https://github.com/user-attachments/assets/b32de86e-d18e-4223-a9d9-b52236dedc35)
> 
> -  ~1min after properly handled client disconnect and disconnect spike:
> ![Screenshot 2024-12-02 104927](https://github.com/user-attachments/assets/b838a8c4-5f24-4c47-80e9-852fdfcfdb0e)
> 
> It seems strange that would be environment-dependent, honestly not sure what could be going on here.

top/btop/htop show the memory *given by the OS* not the memory used by the program. The allocator may hold the memory even if it is unused. If you use a tool like valgrind or heaptrack you should have the same results as me.

**Comment by tristanpoland** [comment]
> > > So what I conclude is that it is more an issue related to sockets not being closed properly. Either from the client side or from the server side. However it appears that even if they are not closed properly after the ping delay + timeout (~25s) by default everything is cleaned up: ![image](https://private-user-images.githubusercontent.com/26095587/391588936-e0d0af02-c17f-4621-8cd2-3dd2199aa3da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTI4ODcsIm5iZiI6MTczMzE1MjU4NywicGF0aCI6Ii8yNjA5NTU4Ny8zOTE1ODg5MzYtZTBkMGFmMDItYzE3Zi00NjIxLThjZDItM2RkMjE5OWFhM2RhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE1MTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYjViODg2ZDMxNWE5MWIyNWQ4OTdiN2ZhOTI2ZjhlOTdmZWFlNzY3NDg4NzVhYjgxYzU5Y2E0ODQzNmQzZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JhQOnWDkMmpZ6Yx-mMHvxzSFNyRTzR9z3QNny21zdS0)
> > > I'll investigate to check why they are not removed before the timeout, but it is not as critic as it seems to be.
> > > @tristanpoland could you confirm on your side that after ~30s memory is correctly cleaned up?
> > 
> > 
> > So without handling the disconnects the memory stays up (64M above baseline) even after 30 sec.
> > With the corrected client code that hangs up properly the memory spikes after the disconnects are called but never goes back down to normal:
> > 
> > * Idle memory:
> >   ![Screenshot 2024-12-02 104827](https://private-user-images.githubusercontent.com/34868944/391612008-72154c25-c78a-4e37-a9da-78860f9e9c99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTc0NjMsIm5iZiI6MTczMzE1NzE2MywicGF0aCI6Ii8zNDg2ODk0NC8zOTE2MTIwMDgtNzIxNTRjMjUtYzc4YS00ZTM3LWE5ZGEtNzg4NjBmOWU5Yzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE2MzI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1M2Y0Y2Y2MTU5ZDlkMzA0MGE1NjYzYzcxMWViNjkxNmE3YWU3NTM2ZDI0MjQ5Y2IxY2Y2Yzc5YTQ0MGVhNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BO48zBgDzhssWOhztXXVJuKhbkWmrhEflaoL5mlEG1Y)
> > * Clients connected peak memory:
> >   ![Screenshot 2024-12-02 104851](https://private-user-images.githubusercontent.com/34868944/391612134-b32de86e-d18e-4223-a9d9-b52236dedc35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTc0NjMsIm5iZiI6MTczMzE1NzE2MywicGF0aCI6Ii8zNDg2ODk0NC8zOTE2MTIxMzQtYjMyZGU4NmUtZDE4ZS00MjIzLWE5ZDktYjUyMjM2ZGVkYzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE2MzI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwMWI5ZTc5ZDYzZDFjOTJjMjdiYWRiOTEzZjBlNzQ5MDc5MTlmMzZkZTM5YWJiMDg5NzBiYmMyN2ZlMDFlM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nBShv8zuZ2D2WkuOgS7qb1vNwZ78Vwg2QIV-qtknz6U)
> > * ~1min after properly handled client disconnect and disconnect spike:
> >   ![Screenshot 2024-12-02 104927](https://private-user-images.githubusercontent.com/34868944/391612337-b838a8c4-5f24-4c47-80e9-852fdfcfdb0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTc0NjMsIm5iZiI6MTczMzE1NzE2MywicGF0aCI6Ii8zNDg2ODk0NC8zOTE2MTIzMzctYjgzOGE4YzQtNWYyNC00YzQ3LTgwZTktODUyZmRmY2ZkYjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE2MzI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYjA1YTIzNjFmNDI4NDNkM2UyMGEwYjkwZmVhNjdlMjgxYzlhNTQ1M2I0NDkwNzZjMmViZDk3MGNlOTI5NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7_Hfvg_6Itg_PImHwVf3IumfC_x21Ww15qwbfUbYaic)
> > 
> > It seems strange that would be environment-dependent, honestly not sure what could be going on here.
> 
> top/btop/htop show the memory _given by the OS_ not the memory used by the program. The allocator may hold the memory even if it is unused. If you use a tool like valgrind or heaptrack you should have the same results as me.

Good to know. Seems to work now 👍🏻
