### ISSUE TITLE
Set up code formatting

### ISSUE THREAD

**Issue by sleeyax** [Totodore/socketioxide#42]
It would be an improvement if to have automatic code formatting so code is always formatted nicely before it reaches the repository. We could do this by enabling auto-format on save at the IDE/text editor level or by creating a git 'before commit' hook to format staged files. Usually [rustfmt](https://github.com/rust-lang/rustfmt) is fine but I suppose we could look into stricter formatting tools/standards, I'll leave that decision up to you.

**Comment by Totodore** [comment]
Yes I totally agree with you. If there is bad formated code it is my fault because I don't have format on save, so sometimes I forget to reformat.
The before commit hook solution seems really cool. I never implemented this but I'll check it.

**Comment by sleeyax** [comment]
I actually forgot to format too so definitely not blaming anyone here 😅

In the JS world husky is often used to set up git hooks easily and there's a Rust equivalent for it: https://github.com/rhysd/cargo-husky

I'm unaware what approach most Rust developers usually take though.
