### ISSUE TITLE
Vacations: I'm completly out from the 5th of july until the 24th.

### ISSUE THREAD

**Issue by Totodore** [Totodore/socketioxide#54]
So I'm doing a break from the **5th of july until the 24th** and won't be able to answer to any issue or doing any code review.

But even without me don't hesitate to contribute by making PR and issues ! I'll try to address everything when I return.

**Comment by sleeyax** [comment]
Ouch, sounds like I need to speed up my game :smile: Thanks for letting us know and enjoy your vacation! :palm_tree:

**Comment by Totodore** [comment]
I'm back :)
