### ISSUE TITLE
How join a socket to room and emitting to room?

### ISSUE THREAD

**Issue by venusdharan** [Totodore/socketioxide#63]
Hi,
Is there any methods to join to room like in nodejs socket io? , in node, we can do something like `socket.join("room name")` or do I need to create a struct with arc and add a socket to it?

I am a noob in Rust, so I am comparing nodejs socket io and this repo examples to get an idea.

**Comment by Totodore** [comment]
Hi, 

Please check the [chat example](https://github.com/Totodore/socketioxide/blob/main/examples/src/chat/handlers.rs#L54). It shows how to use rooms.
