### ISSUE TITLE
Unknown panic

### ISSUE THREAD

**Issue by Dorbmon** [Totodore/socketioxide#64]
I got panic on my online server:
```A panic occurred at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/socketioxide-0.3.0/src/socket.rs:362: called `Result::unwrap()` on an `Err` value: "Closed(..)```
Hope this message can help to determine the error.

**Comment by Totodore** [comment]
Can you try to check if there is the same problem on the main branch? A lot of things have been patched but I haven't released a new version yet.

**Comment by Dorbmon** [comment]
ok, I will switch to master
