### ISSUE TITLE
Can I use it for production?

### ISSUE THREAD

**Issue by LittleTasteOfHeaven** [Totodore/socketioxide#65]
I am building a axum server and want to use your socketio library. Is it safe to use this in production?

**Comment by Totodore** [comment]
Clearly no, it needs some testing to be really safe and also future versions. v0.0.3 has currently some bugs (see #64) (already fixed on main though) 
If you want to use it and see what is wrong so you could report errors, it would be great. But don't use this if you wan't something really stable.

**Comment by LittleTasteOfHeaven** [comment]
Thanks for your response. I see a planned feature of "State recovery when a socket reconnects". How vulnerable a production server is without it?

**Comment by Totodore** [comment]
It is not the main problem, the state recovery is a feature that is currently not implemented but the main problem is unhandled panics or protocol/security concerns
