### ISSUE TITLE
Is there any middleware support where I can check if authentication is ok before the "connection" event fires on the socket?

### ISSUE THREAD

**Issue by LittleTasteOfHeaven** [Totodore/socketioxide#66]
I saw a similar feature in node js socketio server (middlewares). Also, where are the reserved events, such as "connection", "disconnect" etc?

**Comment by Totodore** [comment]
You can use the whole ecosystem of middlewares from [tower-http](https://docs.rs/tower/latest/tower/) that is available for Axum.
Check the use of `CorsLayer` in the chat example and you can do the same with the [AsyncRequireAuthorizationLayer](https://docs.rs/tower-http/0.4.3/tower_http/auth/async_require_authorization/index.html).

With that you will protect you're entire server. If you want to only protect a `namespace` you can do the same thing than in the [chat example](https://github.com/Totodore/socketioxide/blob/14d7233e01bae6b0dee586b6a20e89efe5ea7338/examples/src/chat/handlers.rs#L16C1-L26C6). You just need the [`SocketReq`](https://docs.rs/engineioxide/0.3.0/engineioxide/socket/struct.SocketReq.html) data that is in the `socket.handshake` struct. With that you will be able to get your headers/uri to access credentials.

**Comment by LittleTasteOfHeaven** [comment]
Thanks for your response. What about the reserved events that we can see in the node js socket io server, such as "connection", "disconnect" etc?

**Comment by Totodore** [comment]
There is no custom event for the moment, there is PR open to have a disconnect event #41. There is no connect event planned but the content of the handler will be trigger when you're socket is connected
