### ISSUE TITLE
How do we access a namespace and get all/specific sockets in it?

### ISSUE THREAD

**Issue by LittleTasteOfHeaven** [Totodore/socketioxide#68]
In the example, an `nsHandler` is returned from this code:

```rs
let ns = Namespace::builder().add("/", handlers::handler).build();
```

Which is not a `NameSpace` type and I can't get the sockets inside the "/" path.

I see a method called `get_sockets` implemented in `NameSpace` type. I was hoping to use this method.

Is there a way to do this? Possibly, upholding the namespaces in gobal scope and accessing them from different http routes when needed?

**Comment by Totodore** [comment]
If you want to use sockets outside of the handler declaration please check this : 
https://github.com/Totodore/socketioxide/issues/60#issuecomment-1648497492.

And please for further questions, please open threads on [discussions/q&a](https://github.com/Totodore/socketioxide/discussions/categories/q-a)
